---

- hosts: all
  become: true
  tasks: 

  - name: install httpd
    yum: 
      name: httpd
      state: latest
      enabled: yes:

  - name: start httpd
    service: 
      name: httpd
      state: started
    when: ansible_distribution == "Rocky"


