---
- hosts: all 
  become: yes
  tasks:
    - name: Install nginx
      apt:
         name: nginx
         state: present
         update_cache: yes
      tags: 
        - apt_get


    - name: Create user serge
      user:
        name: Serge
        comment: serge Tomson
        shell:  /bin/bash
    - name: Create group
      group:
        name: Cloudteam
        state: present
    - name: Install httpd
      package:
        name: httpd
        state: present
      when:  ansible_os_family=="Redhat"
    - name: Start httpd if not restart
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="Redhat"

    - name: Install apache2 on ubuntu server
      package:
        name: apache2 
        state: present
      when: ansible_os_family=="Debian"

    - name: Create index file
      file: 
        path: /var/www/html/index.html
        state: touch
      register: index_output
    - name: Create directory
      file: 
         path: /tmp/os
         state: directory
    - name: Copy content to index
      copy:
        dest: file_output.diff.before.path
        content: '<h1>This is created using ansible</h1>'


