---
- hosts: all
  become: true
  tasks:

  - name: install update (Ubuntu)
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (Redhat)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install apache and libapche-mod-php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: webserver
  become: true
  tasks:


  - name: install apache and php for Redhat servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Redhat"
  
- hosts: webserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest

