---
- hosts: all
  become: true
  tasks:

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (Redhat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat, Rocky"

  - name: install apache and libapche-mod-php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: dev
  become: true 
  tasks:
  - name: install unzip
    yum: 
      name: unzip

- hosts: webserver
  become: true
  tasks:


  - name: install apache and php for Redhat servers
    tags: apache,centos,httpd
    yum:
      name:
        - httpd
        - php
        - curl
        - nfs-utils
      state: latest
    when: ansible_distribution == "Rocky Redhat"

- hosts: all 
  become: true
  tasks:

  - name: Create user simone on all target servers
    user:
      name: simone
      group: root
  
  - name: add ssh key for simone
    authorized_key:
      user: simone
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9y3vl7OLkIgzIqnpGkbj8Lod2mPpYlh/Aux0TFxwmi ansible_controller_key"

  - name: add sudoers file for simone
    copy: 
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440



  - name: start httpd (Rocky Redhat)
    tags: apache,Redhat,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Rocky Redhat"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
- hosts: webserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: apache,apache2,webserver
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat, Rocky"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest
  
  tasks:

  - name: Create user simone on all target servers
    user:
      name: simone
      group: root

  - name: add ssh key for simone
    authorized_key:
      user: simone
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9y3vl7OLkIgzIqnpGkbj8Lod2mPpYlh/Aux0TFxwmi ansible_controller_key"

  - name: add sudoers file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440



  - name: start httpd (Rocky Redhat)
    tags: apache,Redhat,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Rocky Redhat"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: webserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: apache,apache2,webserver
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat, Rocky"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest


  tasks:

  - name: Create user simone on all target servers
    user:
      name: simone
      group: root

  - name: add ssh key for simone
    authorized_key:
      user: simone
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9y3vl7OLkIgzIqnpGkbj8Lod2mPpYlh/Aux0TFxwmi ansible_controller_key"

  - name: add sudoers file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440



  - name: start httpd (Rocky Redhat)
    tags: apache,Redhat,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Rocky Redhat"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: webserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: apache,apache2,webserver
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat, Rocky"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest


