---
- hosts: all
  become: true
  tasks:

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (Redhat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install apache and libapche-mod-php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: webserver
  become: true
  tasks:


  - name: install apache and php for Redhat servers
    tags: apache,centos,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Redhat"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
- hosts: webserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: apache,apache2,webserver
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package
    package:
      name: samba
      state: latest

